apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygencs-deployment
  labels:
    app: oxygencs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oxygencs
  template:
    metadata:
      labels:
        app: oxygencs
    spec:
      containers:
      - name: oxygencs
        image: zipthezap/log680-python:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 64m
          limits:
            memory: 64Mi
            cpu: 64m