## To implement
jobs:
  install-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

  build:
    needs: install-packages
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build

  test:
    needs: install-packages
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: npm run test

  lint:
    needs: install-packages
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint