
name: Python package

on: [push]
env :
  test_token: ${{secrets.DOCKER_CODE}}
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip     
          pip install -r requirements.txt
      - name: Lint with pylint
        env:
          TOKEN: ${{secrets.DOCKER_CODE}}
        run: |
          # Run pylint on your Python files
          pylint $(git ls-files '*.py')
      - name: Test with unittest
        run: |
          # Run unittest on your test files
          python -m unittest discover -s test -p "*test.py"
